import json,os
import numpy as np,pandas as pd
O='architecture_validation';new=pd.read_csv(O+'/construct_features.csv').set_index('construct');old=pd.read_csv('extended/all_construct_features.csv').set_index('construct');za=np.load(O+'/arrays.npz');zo=np.load('extended/construct_arrays.npz');seq=json.load(open('previous/results/sequences.json'));oldmap=json.load(open('extended/core_mapping.json'));orders=json.load(open('extended/architecture_groups.json'));names=sorted(set(za['names'])|set(zo['names']));arrays={k:np.stack([(zo[k][list(zo['names']).index(n)] if n in zo['names'] else za[k][list(za['names']).index(n)]) for n in names]) for k in ['cp','pae','density','plddt','rna']};# RNA semantics: original arrays rna=sum; use original rna_max for consistent max annotation.
for i,n in enumerate(names):
 if n in zo['names']:arrays['rna'][i]=zo['rna_max'][list(zo['names']).index(n)]
meta=json.load(open(O+'/mapping.json'));rows=[];cpcols=json.load(open('combined12/manifest.json'))['feature_sets']['CP_summary14']
for ci,n in enumerate(names):
 if n in old.index:
  v=old.loc[n];mp=np.array(oldmap[n]);meta[n]=dict(mapping=mp.tolist(),protein_length=int(v.protein_length),uploaded_length=int(v.protein_length),repeat_count=int((mp>=0).sum()/36),source_order=orders[n],batch='previous',success=int(v.success),rna=seq[n]['rna']);r=dict(construct=n,**{k:meta[n][k] for k in ['success','protein_length','uploaded_length','repeat_count','source_order','batch','rna']},n_seeds=4,n_models=20,**{c:float(v[c]) for c in cpcols},plddt_protein_mean=v.plddt_protein_mean,pae_contact_weighted=v.pae_contact_weighted,Rg=v.Rg_CA_A,Rg_full_length_normalized=v.Rg_full_length_normalized,anisotropy=v.core_anisotropy)
 else:
  v=new.loc[n];mp=np.array(meta[n]['mapping']);r=v[['success','protein_length','uploaded_length','repeat_count','source_order','batch','rna','n_seeds','n_models']+cpcols+['plddt_protein_mean','pae_contact_weighted','Rg','Rg_full_length_normalized','anisotropy']].to_dict();r['construct']=n
 ac=arrays['cp'][ci];ap=arrays['pae'][ci];pl=arrays['plddt'][ci];valid=mp>=0;mask=np.triu(valid[:,None]&valid[None,:],1);gap=abs(mp[:,None]-mp[None,:]);hc=mask&(gap>=12)&(ac>.5)&(ap<5)&(pl[:,None]>=80)&(pl[None,:]>=80);r.update(plddt_core_mean=float(np.nanmean(pl)),plddt_core_min=float(np.nanmin(pl)),global_core_PAE=float(ap[mask].mean()),HC_nonlocal_density=float(hc.sum()/valid.sum()),compactness=float(r['protein_length']/(4*np.pi*r['Rg']**3/3)));ad=[];no=[];pa=[];internal=[]
 for i in range(int(r['repeat_count'])):
  ii=np.arange(i*36,(i+1)*36);sm=np.triu(gap[np.ix_(ii,ii)]>=4,1);r[f'internal_P{i+1}']=float(ac[np.ix_(ii,ii)][sm].sum()/36);internal.append(r[f'internal_P{i+1}'])
  for j in range(i+1,int(r['repeat_count'])):
   jj=np.arange(j*36,(j+1)*36);sm=gap[np.ix_(ii,jj)]>=4;key=f'P{i+1}_P{j+1}';r[key+'_CP']=float(ac[np.ix_(ii,jj)][sm].mean());r[key+'_PAE']=float(ap[np.ix_(ii,jj)][sm].mean());(ad if j==i+1 else no).append(r[key+'_CP']);
   if j==i+1:pa.append(r[key+'_PAE'])
 r.update(adj_CP_mean=np.mean(ad),adj_CP_min=min(ad),nonadj_CP_mean=np.mean(no),adj_PAE_mean=np.mean(pa),internal_CP_mean=np.mean(internal));r['K204_slot_density']=arrays['density'][ci,170];r['A235_slot_density']=arrays['density'][ci,201];r['CCR01_fixed']=arrays['density'][ci,144:147].mean();rows.append(r)
a=pd.DataFrame(rows);groups=sorted(a.source_order.unique());a['architecture']=a.source_order.map({g:'G%02d'%(i+1) for i,g in enumerate(groups)});a.to_csv(O+'/all_features.csv',index=False);main=a[(a.repeat_count==12)&(a.batch!='TRM')];assert len(main)==24 and main.success.sum()==4;main.to_csv(O+'/main_features.csv',index=False);main[['construct','architecture','source_order','success','protein_length','batch','n_seeds','n_models']].to_csv(O+'/construct_registry.csv',index=False);np.savez_compressed(O+'/all_arrays.npz',names=names,**arrays);json.dump(meta,open(O+'/all_mapping.json','w'),indent=2)
rm=pd.read_csv(O+'/residue_mapping.csv');om=pd.read_csv('extended/residue_mapping_all_constructs.csv');om=om.rename(columns={'repeat_slot':'slot','repeat_position':'position','loop_near_5aa':'near_loop_5'});om['analysis_residue']=om.native_residue;om['source']=[int(orders[r.construct].split(',')[int(r.slot)-1]) for r in om.itertuples()];pd.concat([om[rm.columns],rm],ignore_index=True).to_csv(O+'/all_residue_mapping.csv',index=False)
# Verify all previously reported summary features survive re-extraction unchanged within numerical precision.
b=pd.read_csv('combined12/training_data.csv').set_index('construct');check=main.set_index('construct').loc[b.index];d=np.abs(check[cpcols].to_numpy()-b[cpcols].to_numpy());assert d.max()<1e-3,d.max();json.dump({'max_abs_summary_difference':float(d.max()),'original_arrays_reused':True,'original_second_zip_local_copy_truncated':True,'confidence_definition':'core minimum of construct-average residue pLDDT; HC thresholds applied after model/seed CP averaging','main_n':24,'main_success':4},open(O+'/validation.json','w'),indent=2);print(main.groupby(['architecture','source_order']).success.agg(['count','sum']).to_string())
